databases:
  - name: project4db
    plan: free
    databaseName: project4
    user: project4

services:
  - type: web
    plan: free
    name: project4
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn project4.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: project4db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4